openapi: 3.0.0
info:
title : AI Clinical Assistant API
  version: 1.0.0
  description: This API provides endpoints for an AI-powered clinical assistant that supports  patient examination and diagnosis.

paths:
  /symptoms:
    post:
      summary: Analyze patient-reported symptoms
      description: This endpoint analyzes a list of symptoms and returns a list of potential causes or diagnoses.
      requestBody:
        description: Patient-reported symptoms
        required: true 
        content:
          application/json:
            schema:
              type: object
              properties:
                symptoms:
                  type: array
                  description: Array of symptoms reported by the patient
                  items:
                    type: string
                    example: Fever
                    minLength: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  potential_causes:
                    type: array
                    description: List of potential causes for the reported symptoms
                    items :
                      type: string
                      example: Influenza
                      minLength: 1
                  potential_diagnoses:
                    type: array
                    description: List of potential diagnoses based on the reported symptoms
                    items:
                      type: string
                      example: Common Cold
                      minLength: 1

  /examination:
    post:
      summary: Guide patient examination
      description: This endpoint provides step-by-step instructions on how to conduct a thorough physical examination.
      requestBody:
        description: Patient information and symptoms
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient_info:
                  type: object
                  description: Patient's personal information
                  properties:
                    age:
                      type: integer
                      description: Age of the patient
                      example: 35
                      minimum: 0
                    gender:
                      type: string
                      description: Gender of the patient
                      example: Male
                      enum: [Male, Female]
                    medical_history:
                      type: string
                      description: Brief medical history of the patient
                      example: Asthma
                      minLength:  1
                symptoms:
                  type: array
                  description: Array of symptoms reported by the patient
                  items:
                    type: string
                    example: Fever
                    minLength: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  examination_steps:
                    type: array
                    description: A list of examination steps to be performed
                    items:
                      type: object
                      properties:
                        description:
                          type: string
                          description: Description of the examination step
                          example: Inspect the throat for redness
                          minLength: 1
                        instructions:
                          type: string
                          description: Instructions on how to perform the examination step
                          example: Use a flashlight to illuminate the throat
                          minLength: 1

  /diagnosis:
    post:
      summary: Suggest possible diagnoses
      description: This endpoint suggests possible diagnoses based on the findings from the physical examination.
      requestBody:
        description: Examination findings
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                examination_findings:
                  type: array
                  description: A list of examination findings
                  items:
                    type: object
                    properties:
                      test_name:
                        type: string
                        description: Name of the test performed
                        example: Throat exam
                        minLength: 1
                      result:
                        type: string
                        description: Result of the test
                        example: Redness
                        minLength: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  possible_diagnoses:
                    type: array
                    description: A list of possible diagnoses based on the examination findings
                    items:
                      type: string
                      example: Tonsillitis
                      minLength: 1
                  recommended_tests:
                    type: array
                    description: A list of recommended tests to further evaluate the patient's condition
                    items:
                      type: string
                      example: Blood test
                      minLength: 1
                  recommended_treatments:
                    type: array
                    description: A list of recommended treatments  for the possible diagnoses
                    items:
                      type: string
                      example: Antibiotics
                      minLength: 1

  /differential-diagnosis:
    post:
      summary: Assist in differential diagnosis
      description: This endpoint assists in narrowing down the possible diagnoses by considering various factors and ruling out less likely conditions.
      requestBody:
        description: Possible diagnoses, patient information, and examination findings
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                possible_diagnoses:
                  type: array
                  description: A list of possible diagnoses to be evaluated
                  items:
                    type: string
                    example: Tonsillitis
                    minLength: 1
                patient_info:
                  type: object
                  description: Patient's personal information
                  properties:
                    age:
                      type: integer
                      description: Age of the patient
                      example: 35
                      minimum: 0
                    gender:
                      type: string
                      description: Gender of the patient
                      example: Male
                      enum: [Male, Female]
                    medical_history:
                      type: string
                      description: Brief medical history of the patient
                      example: Asthma
                      minLength: 1
                examination_findings:
                  type: array
                  description: A list of examination findings
                  items:
                    type: object
                    properties:
                      test_name:
                        type: string
                        description: Name of the test performed
                        example: Throat exam
                        minLength: 1
                      result:
                        type: string
                        description: Result of the test
                        example: Redness
                        minLength: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ranked_diagnoses:
                    type: array
                    description: A list of ranked diagnoses, with the most likely diagnosis at the top
                    items:
                      type: object
                      properties:
                        diagnosis:
                          type: string
                          description: The diagnosis
                          example: Tonsillitis
                          minLength: 1
                        probability:
                          type: number
                          description: The probability of the diagnosis
                          example: 0.8
                          minimum: 0 
                          maximum: 1